<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lawrence &amp; Long Architects  &mdash; homepage </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=1100">

    <script src="<?php echo $config->urls->templates?>dist2/assets/royalslider/jquery-1.8.3.min.js"></script>
    <script src="<?php echo $config->urls->templates?>dist2/assets/royalslider/jquery.royalslider.min.js"></script>
    <link href="<?php echo $config->urls->templates?>dist2/assets/royalslider/royalslider.css" rel="stylesheet">
    <link href="<?php echo $config->urls->templates?>dist2/styles/screen.css" rel="stylesheet">

  </head>

  <body>
    <!--[if lt IE 9]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

	<header>
		<a href="<?php echo $config->urls->root ?>">
			<h1>Lawrence &amp; Long Architects</h1>
		</a>
	</header>

    <div class="wrap">